name: CI

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for better relevancy of analysis
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Specify your node version
      - name: Install dependencies
        run: npm install
      - name: Run tests and generate coverage
        run: npm test -- --code-coverage
      - name: Run SonarCloud Scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
          -Dsonar.projectKey=your_project_key \
          -Dsonar.organization=your_organization_key \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
          -Dsonar.sources=src/app \
          -Dsonar.tests=src \
          -Dsonar.test.inclusions=src/**/*.spec.ts \
          -Dsonar.exclusions=**/node_modules/**,**/dist/** \
          -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info \
          -Dsonar.typescript.lcov.reportPaths=coverage/lcov.info \
          -Dsonar.typescript.tsconfigPath=tsconfig.json